### ISSUE TITLE
Search why tests wich worked in original Esprima fail

### ISSUE THREAD

**Issue by jogibear9988** [node-projects/esprima-next#3]
see following: 

https://github.com/node-projects/esprima-next/commit/e71acdc8c241706954c58cec85dc998373a2c913

**Comment by mfukala** [comment]
Hello Jochen. I wonder if you plan to address this issue. I'm considering adding dependency to this esprima fork but I'm slightly concerned about the quality of the code (taken from esprima's master branch) especially when I see this issue. Thank you for the work you've done for this!

**Comment by jogibear9988** [comment]
My problem is, even if i use orginal esprima, some of the tests fail. I'll look again if Ihave some regressions. But need to look when I've time.

**Comment by mfukala** [comment]
Actually where're the failing results you're referring to? I can only find passing results for main branch:
https://github.com/node-projects/esprima-next/actions?query=branch%3Amain+

Is it green because you've already disabled the failing tests on main branch?

I can see failures on the "workOnEs2022" branch which I supposed have some of your own changes.

**Comment by jogibear9988** [comment]
I've checked this tests, i don't think they worked in esprima
